### PR TITLE
Allow using a link with IDs and not just RID's + other fixes

### LINKED ISSUE #29: How to get the "coll_self_link" without iterating through the databases and collections queries?
Is there a way to get the "coll_self_link" without iterating through the databases and collections queries?
For example, if I know the database and collection names, how can I issue the QueryDocuments call directly:

_, err = client.QueryDocuments(
        "coll_self_link", 
        documentdb.NewQuery("SELECT * FROM ROOT r WHERE r.name=@name", documentdb.P{"@name", "john"}),
        &users,
    )

I tried a URL like specified in the REST API:
'https://{databaseaccount}.documents.azure.com/dbs/{db}/colls/{coll}'

but I get a "BadRequest, Request url is invalid." error.

The same question is also valid for databases and collections.

Thanks.

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
This PR includes three changes:

**First**
Currently, all methods accept a "RID link" (i.e. a "self link") only, such as `dbs/9ihLAA==/colls/9ihLANgYXow=/`

Because RIDs are generated within Cosmos DB, we can't always know them beforehand. There are situations (such as some we're encountering in Dapr) where we have no way to retrieve a RID.

This PR changes the authentication routines to allow passing links with IDs too, such as `dbs/dapre2e/colls/items/`.

**Second**

Certain operations are not possible when requests are authenticated using Azure AD, namely CRUD operations on stored procedures and UDFs (however, invoking a SP is always possible). This change returns an error if a user tries to invoke those methods while being auth'd with Azure AD.

**Third**

This is a minor fix, but it changes the way AAD tokens are refreshed, adding a context and a timeout. This is important because if the refresh requests hangs, we want to have a timeout in place (set to 10 seconds, which should be reasonable).

Note that this is _technically_ a breaking change because it changes the `ServicePrincipalProvider` interface. However, that interface was always used to indicate the need for an `*adal.ServicePrincipalToken`, which implements both methods. So in practice (unless users were using this SDK in unexpected ways), nothing should break.

PS: This fixes #29 too

### CODE REVIEW

File: documentdb.go [hunk 1]
```diff
@@ -117,6 +119,10 @@ func (c *DocumentDB) ReadDocument(link string, doc interface{}, opts ...CallOpti
 
 // Read sporc by self link
 func (c *DocumentDB) ReadStoredProcedure(link string, opts ...CallOption) (sproc *Sproc, err error) {
+	if c.usesAAD() {
+		return nil, errors.New("cannot perform CRUD operatons on stored procedures while authenticating with Azure AD")
```
Comment (a8m) [inline documentdb.go:123]: Can we declare this error once? e.g.

```go
var errAAD = errors.New("cannot perform CRUD operations on stored procedures while authenticating with Azure AD")

/// ...


if c.usesAAD() {
	return nil, errAAD
}
```

There's also a small typo in "operatons => operations".

File: request.go [hunk 2]
```diff
@@ -90,7 +93,9 @@ func (req *Request) DefaultHeaders(config *Config, userAgent string) (err error)
 
 		req.Header.Add(HeaderAuth, url.QueryEscape("type=master&ver=1.0&sig="+sign))
 	} else if config.ServicePrincipal != nil {
-		err := config.ServicePrincipal.EnsureFresh()
+		ctx, cancel := context.WithTimeout(context.Background(), ServicePrincipalRefreshTimeout)
```
Comment (a8m) [inline request.go:96]: Don't we want to use here the request context instead of background? `req.Context()`

**Comment by ItalyPaleAle** [comment]
Thanks @a8m  for the review! Made the changes as requested

**Review by a8m — APPROVED** [review]
